#!/bin/bash

clear
if [[ -e /etc/debian_version ]]; then
	OS=debian
	RCLOCAL='/etc/rc.local'
elif [[ -e /etc/centos-release || -e /etc/redhat-release ]]; then
	OS=centos
	RCLOCAL='/etc/rc.d/rc.local'
	chmod +x /etc/rc.d/rc.local
else
	echo "Nampaknya anda tidak menjalankan installer ini pada sistem Debian, Ubuntu atau CentOS"
	exit
fi
color1='\e[031;1m'
color2='\e[32;1m'
color3='\e[0m'
  echo -e "==================================================================="
  echo -e "             MENU UTAMA | MENU SCRIPT BY Ronn             "
  echo -e "==================================================================="
  echo -e " "
	echo -e "${color2}Menu SSH & OpenVPN${color3}"
  echo -e "------------------"
	echo -e "${color1} 1${color3}) Membuat Akaun Pelanggan              (${color2}user-add${color3})"
	echo -e "${color1} 2${color3}) Membuat Akaun Percubaan Pelanggan    (${color2}trial${color3})"
  echo -e "${color1} 3${color3}) Generate Akaun Percubaan Pelanggan   (${color2}user-generate${color3})"
	echo -e "${color1} 4${color3}) Tambah Masa Aktif Akaun Pelanggan    (${color2}user-aktif${color3})"
	echo -e "${color1} 5${color3}) Ganti Password Akaun Pelanggan       (${color2}user-password${color3})"
	echo -e "${color1} 6${color3}) Padam Akaun Pelanggan                (${color2}user-delete${color3})"
	echo -e "${color1} 7${color3}) Maklumat Akaun Pelanggan             (${color2}user-detail${color3})"
	echo -e "${color1} 8${color3}) Senarai Akaun Pelanggan              (${color2}user-list${color3})"
	echo -e "${color1} 9${color3}) Senarai Pelanggan Yang Sedang Login  (${color2}user-login${color3})"
	echo -e "${color1}10${color3}) Melihat Log Login Dropbear & OpenSSH (${color2}user-log${color3})"
  echo -e "${color1}11${color3}) Lock Akaun Pelanggan                 (${color2}user-lock${color3})"
	echo -e "${color1}12${color3}) Unlock Akaun Pelanggan Yang Dilock   (${color2}user-unlock${color3})"
  echo -e " "
  echo -e "${color2}Menu Akaun Expire${color3}"
  echo -e "-----------------"
  echo -e "${color1}13${color3}) Lock Akaun Pelanggan Yang Expire     (${color2}user-expire${color3})"
	echo -e "${color1}14${color3}) Senarai Pelanggan Yang Akan Expire   (${color2}infouser${color3})"
	echo -e "${color1}15${color3}) Senarai Pelanggan Yang Sudah Expire  (${color2}expireduser${color3})"
	echo -e "${color1}16${color3}) Padam Akaun Pelanggan Yang Expire    (${color2}user-delete-expired${color3})"
  echo -e " "
  echo -e "${color2}Menu Multi Login${color3}"
  echo -e "----------------"
  echo -e "${color1}17${color3}) Manual Kill Multi Login              (${color2}user-limit${color3})"
  echo -e "${color1}18${color3}) Auto Kill Multi Login                (${color2}user-auto-limit${color3})"
  echo -e "${color1}19${color3}) Ban/Lock User Yang Multilogin        (${color2}user-ban${color3})"
	echo -e "${color1}20${color3}) Unban User Yang Dibanned             (${color2}user-unban${color3})"
	echo -e "${color1}21${color3}) Pelanggan Yang Dikick : user-limit   (${color2}log-limit${color3})"
	echo -e "${color1}22${color3}) Pelanggan Yang Dibanned : user-ban   (${color2}log-ban${color3})"
	echo -e " "
	echo -e "${color2}Menu PPTP VPN${color3}"
  echo -e "-------------"
	echo -e "${color1}23${color3}) Membuat Akaun PPTP VPN               (${color2}user-add-pptp${color3})"
	echo -e "${color1}24${color3}) Padam Akaun PPTP VPN                 (${color2}user-delete-pptp${color3})"
	echo -e "${color1}25${color3}) Maklumat Akaun PPTP VPN              (${color2}user-detail-pptp${color3})"
	echo -e "${color1}26${color3}) Senarai User PPTP VPN yang login     (${color2}user-login-pptp${color3})"
	echo -e "${color1}27${color3}) Senarai User PPTP VPN                (${color2}alluser-pptp${color3})"
	echo -e " "
	echo -e "${color2}Menu VPS${color3}"
  echo -e "--------"
	echo -e "${color1}28${color3}) Speedtest Server                     (${color2}speedtest --share${color3})"
	echo -e "${color1}29${color3}) Benchmark Server                     (${color2}bench-network${color3})"
	echo -e "${color1}30${color3}) Jumlah Penggunaan RAM server         (${color2}ram${color3})"
if [[ "$OS" = 'debian' ]]; then 
	echo -e "${color1}31${color3}) Restart OpenSSH                      (${color2}service ssh restart${color3})"
	echo -e "${color1}32${color3}) Restart Dropbear                     (${color2}service dropbear restart${color3})"
	echo -e "${color1}33${color3}) Restart OpenVPN                      (${color2}service openvpn restart${color3})"
	echo -e "${color1}34${color3}) Restart PPTP VPN                     (${color2}service pptpd restart${color3})"
	echo -e "${color1}35${color3}) Restart Webmin                       (${color2}service webmin restart${color3})"
	echo -e "${color1}36${color3}) Restart Squid Proxy                  (${color2}service squid3 restart${color3})"
else
	echo -e "${color1}31${color3}) Restart OpenSSH                      (${color2}service sshd restart${color3})"
	echo -e "${color1}32${color3}) Restart Dropbear                     (${color2}service dropbear restart${color3})"
	echo -e "${color1}33${color3}) Restart OpenVPN                      (${color2}service openvpn restart${color3})"
	echo -e "${color1}34${color3}) Restart PPTP VPN                     (${color2}service pptpd restart${color3})"
	echo -e "${color1}35${color3}) Restart Webmin                       (${color2}service webmin restart${color3})"
	echo -e "${color1}36${color3}) Restart Squid Proxy                  (${color2}service squid restart${color3})"
fi
  echo -e "${color1}37${color3}) Edit Port Server                     (${color2}edit-port${color3})"
  echo -e "${color1}38${color3}) Set Auto Reboot Pada Server          (${color2}auto-reboot${color3})"
  echo -e "${color1}39${color3}) Reboot Server                        (${color2}reboot${color3})"
  echo -e "${color1}40${color3}) Tukar Password Server                (${color2}passwd${color3})"
  echo -e "${color1}41${color3}) Log installation                     (${color2}log-install${color3})"
  echo -e "==================================================================="
  echo -e "              SCRIPT BY Ronn | TESTER HACKER              "
  echo -e "==================================================================="
  read -p "Masukkan Nombor Pilihan Anda (nombor): " x
  echo -e " "
if test $x -eq 1; then
user-add
elif test $x -eq 2; then
trial
elif test $x -eq 3; then
user-generate
elif test $x -eq 4; then
user-aktif
elif test $x -eq 5; then
user-password
elif test $x -eq 6; then
user-delete
elif test $x -eq 7; then
user-detail
elif test $x -eq 8; then
user-list
elif test $x -eq 9; then
user-login
elif test $x -eq 10; then
user-log
elif test $x -eq 11; then
user-lock
elif test $x -eq 12; then
user-unlock
elif test $x -eq 13; then
echo "Script ini berjalan secara automatik setiap jam 12 malam"
echo "Anda tidak perlu menjalankannya secara manual"
echo "Jika anda tetap ingin menjalankan script ini, taip user-expire"
elif test $x -eq 14; then
clear
infouser
elif test $x -eq 15; then
clear
expireduser
elif test $x -eq 16; then
user-delete-expired
elif test $x -eq 17; then
clear
read -p "Isikan Jumlah Maximal Login (1-2): " MULTILOGIN
user-limit $MULTILOGIN
elif test $x -eq 18; then
user-auto-limit
elif test $x -eq 19; then
read -p "Isikan Jumlah Maximal Login (1-2): " MULTILOGIN
user-ban $MULTILOGIN
elif test $x -eq 20; then
user-unban
elif test $x -eq 21; then
clear
log-limit
elif test $x -eq 22; then
clear
log-ban
elif test $x -eq 23; then
user-add-pptp
elif test $x -eq 24; then
user-delete-pptp
elif test $x -eq 25; then
user-detail-pptp
elif test $x -eq 26; then
user-login-pptp
elif test $x -eq 27; then
alluser-pptp
elif test $x -eq 28; then
speedtest --share
elif test $x -eq 29; then
bench-network
elif test $x -eq 30; then
ram
elif test $x -eq 31; then
	if [[ "$OS" = 'debian' ]]; then 
		service ssh restart 
	else 
		service sshd restart 
	fi
elif test $x -eq 32; then
service dropbear restart
elif test $x -eq 33; then
service openvpn restart
elif test $x -eq 34; then
	if [[ "$OS" = 'debian' ]]; then 
		service pptpd restart 
	else 
		service pptpd restart 
	fi
elif test $x -eq 35; then
service webmin restart
elif test $x -eq 36; then
	if [[ "$OS" = 'debian' ]]; then 
		service squid3 restart 
	else 
		service squid restart 
	fi
elif test $x -eq 37; then
edit-port
elif test $x -eq 38; then
auto-reboot
elif test $x -eq 39; then
reboot
elif test $x -eq 30; then
passwd
elif test $x -eq 41; then
log-install
else
echo "Pilihan Tidak Terdapat Di Menu."
exit
fi
